# Numpy
NumPy - Numerical Python is a fundamental library for scientific computing in Python. It provides support for arrays and matrices along with a collection of mathematical functions to operate on these data structures.

In [1]:
import numpy as np

In [2]:
# Creating arrays
arr1 = np.array([1,2 ,3, 4, 5])

In [3]:
print(arr1)
print(arr1.shape)

[1 2 3 4 5]
(5,)


In [4]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5)

array([[1, 2, 3, 4, 5]])

In [5]:
arr2 = np.array([[1, 2, 3, 4, 5]])
print(arr2.shape)

(1, 5)


In [6]:
arr3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.arange(0, 10, 1).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# Attributes of Numpy array
arr4 = np.array([[1, 2, 3],[4, 5, 6]])

print("Array: ", arr4)
print("Shape: ", arr4.shape)
print("Number of dimensions: ", arr4.ndim)
print("Size (number of elements): ", arr4.size)
print("Data type: ", arr4.dtype)
print("Item size (in bytes): ", arr4.itemsize)

Array:  [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Data type:  int64
Item size (in bytes):  8


In [12]:
# Numpy vectorized operations
arr_a = np.array([1, 2, 3, 4, 5])
arr_b = np.array([10, 20, 30, 40, 50])

# Element wise addition
print("Addition", arr_a + arr_b)

# Element wise subtraction
print("Subtraction: ", arr_a-arr_b)

# Element wise multiplication
print("Multiplication: ", arr_a*arr_b)

# Element wise division
print("Division: ", arr_a / arr_b)

Addition [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [13]:
# Universal Functions

print("Sqrt: ", np.sqrt(arr_a))

print("Exponential: ", np.exp(arr_a))

print("Sine: ", np.sin(arr_a))

print("Cosine: ", np.cos(arr_a))

print("Log: ", np.log(arr_a))

Sqrt:  [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Log:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [14]:
# Array slicing and indexing

arr7 = np.array([[1, 2, 3,4 ], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array \n", arr7)

Array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
arr7[0][0]

np.int64(1)

In [16]:
arr7[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
# Statistical Concepts

data = np.array([1, 2, 3, 4, 5])

mean = np.mean(data)
std_dev = np.std(data)

normalised_data = (data-mean)/std_dev

print(normalised_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [19]:
median = np.median(data)

variance = np.var(data)

print(median, variance)

3.0 2.0


In [24]:
# Logical Oerations

data = np.array([1, 2,3, 4, 45, 6, 7, 8, 9, 10])

data[(data>5) & (data<=8)]

array([6, 7, 8])